export const Profiles = [
    {
        id :"IDUH89398Ha",
        image :"/profile.png",
        name : "Daniel Kebede",
        title : "BSC in Mathematics",
        bio: "Something about themself and what they do goes here. Something about themself and what they do goes here.",
        cost : "5",
        rating: 4.6,
    },
    {
        id :"IDUH89398Hb",
        image :"/profile.png",
        name : "Liyu Kebede",
        title : "BSC in Mathematics",
        bio: "Something about themself and what they do goes here. Something about themself and what they do goes here.",
        cost : "15",
        rating: 4.6,
    },
    {
        id :"IDUH89398Hc",
        image :"/profile.png",
        name : "Maedot Kebede",
        title : "BSC in Mathematics",
        bio: "Something about themself and what they do goes here. Something about themself and what they do goes here.",
        cost : "50",
        rating: 4.6,
    },
    {
        id :"IDUH89398Hd",
        image :"/profile.png",
        name : "Fenet Kebede",
        title : "BSC in Mathematics",
        bio: "Something about themself and what they do goes here. Something about themself and what they do goes here.",
        cost : "10",
        rating: 4.6,
    },
    {
        id :"IDUH89398He",
        image :"/profile.png",
        name : "Meaza Kebede",
        title : "BSC in Mathematics",
        bio: "Something about themself and what they do goes here. Something about themself and what they do goes here.",
        cost : "5",
        rating: 4.6,
    },
    {
        id :"IDUH89398Hf",
        image :"/profile.png",
        name : "Mahlet Kebede",
        title : "BSC in Mathematics",
        bio: "Something about themself and what they do goes here. Something about themself and what they do goes here.",
        cost : "5",
        rating: 4.6,
    },
    {
        id :"IDUH89398Hg",
        image :"/profile.png",
        name : "Daniel Kebede",
        title : "BSC in Mathematics",
        bio: "Something about themself and what they do goes here. Something about themself and what they do goes here.",
        cost : "5",
        rating: 4.6,
    },
    {
        id :"IDUH89398Hh",
        image :"/profile.png",
        name : "Daniel Kebede",
        title : "BSC in Mathematics",
        bio: "Something about themself and what they do goes here. Something about themself and what they do goes here.",
        cost : "5",
        rating: 4.6,
    },
    {
        id :"IDUH89398Hi",
        image :"/profile.png",
        name : "Daniel Kebede",
        title : "BSC in Mathematics",
        bio: "Something about themself and what they do goes here. Something about themself and what they do goes here.",
        cost : "5",
        rating: 4.6,
    },
    {
        id :"IDUH89398Hj",
        image :"/profile.png",
        name : "Daniel Kebede",
        title : "BSC in Mathematics",
        bio: "Something about themself and what they do goes here. Something about themself and what they do goes here.",
        cost : "5",
        rating: 4.6,
    },
    {
        id :"IDUH89398Hk",
        image :"/profile.png",
        name : "Daniel Kebede",
        title : "BSC in Mathematics",
        bio: "Something about themself and what they do goes here. Something about themself and what they do goes here.",
        cost : "5",
        rating: 4.6,
    },
    {
        id :"IDUH89398Hl",
        image :"/profile.png",
        name : "Daniel Kebede",
        title : "BSC in Mathematics",
        bio: "Something about themself and what they do goes here. Something about themself and what they do goes here.",
        cost : "5",
        rating: 4.6,
    },
    {
        id :"IDUH89398Hm",
        image :"/profile.png",
        name : "Daniel Kebede",
        title : "BSC in Mathematics",
        bio: "Something about themself and what they do goes here. Something about themself and what they do goes here.",
        cost : "5",
        rating: 4.6,
    },
    {
        id :"IDUH89398Hn",
        image :"/profile.png",
        name : "Daniel Kebede",
        title : "BSC in Mathematics",
        bio: "Something about themself and what they do goes here. Something about themself and what they do goes here.",
        cost : "5",
        rating: 4.6,
    },
]



export const Courses = [
    {
        id : "ifuinrfin",
        image : "/cour1.png",
        title : "Learn Python",
        description : "Understanding Basic algorithms and data structures with python, and practices on competative programming sites.",
        enroll : "40+ Enroll",
    },    {
        id : "ifuinrfin",
        image : "/cour1.png",
        title : "Learn Python",
        description : "Understanding Basic algorithms and data structures with python, and practices on competative programming sites.",
        enroll : "40+ Enroll",
    },    {
        id : "ifuinrfin",
        image : "/cour1.png",
        title : "Learn Python",
        description : "Understanding Basic algorithms and data structures with python, and practices on competative programming sites.",
        enroll : "40+ Enroll",
    },    {
        id : "ifuinrfin",
        image : "/cour1.png",
        title : "Learn Python",
        description : "Understanding Basic algorithms and data structures with python, and practices on competative programming sites.",
        enroll : "40+ Enroll",
    },    {
        id : "ifuinrfin",
        image : "/cour1.png",
        title : "Learn Python",
        description : "Understanding Basic algorithms and data structures with python, and practices on competative programming sites.",
        enroll : "40+ Enroll",
    },    {
        id : "ifuinrfin",
        image : "/cour1.png",
        title : "Learn Python",
        description : "Understanding Basic algorithms and data structures with python, and practices on competative programming sites.",
        enroll : "40+ Enroll",
    },    {
        id : "ifuinrfin",
        image : "/cour1.png",
        title : "Learn Python",
        description : "Understanding Basic algorithms and data structures with python, and practices on competative programming sites.",
        enroll : "40+ Enroll",
    },    {
        id : "ifuinrfin",
        image : "/cour1.png",
        title : "Learn Python",
        description : "Understanding Basic algorithms and data structures with python, and practices on competative programming sites.",
        enroll : "40+ Enroll",
    },    {
        id : "ifuinrfin",
        image : "/cour1.png",
        title : "Learn Python",
        description : "Understanding Basic algorithms and data structures with python, and practices on competative programming sites.",
        enroll : "40+ Enroll",
    },    {
        id : "ifuinrfin",
        image : "/cour1.png",
        title : "Learn Python",
        description : "Understanding Basic algorithms and data structures with python, and practices on competative programming sites.",
        enroll : "40+ Enroll",
    },    {
        id : "ifuinrfin",
        image : "/cour1.png",
        title : "Learn Python",
        description : "Understanding Basic algorithms and data structures with python, and practices on competative programming sites.",
        enroll : "40+ Enroll",
    },    {
        id : "ifuinrfin",
        image : "/cour1.png",
        title : "Learn Python",
        description : "Understanding Basic algorithms and data structures with python, and practices on competative programming sites.",
        enroll : "40+ Enroll",
    },    {
        id : "ifuinrfin",
        image : "/cour1.png",
        title : "Learn Python",
        description : "Understanding Basic algorithms and data structures with python, and practices on competative programming sites.",
        enroll : "40+ Enroll",
    },    {
        id : "ifuinrfin",
        image : "/cour1.png",
        title : "Learn Python",
        description : "Understanding Basic algorithms and data structures with python, and practices on competative programming sites.",
        enroll : "40+ Enroll",
    },    {
        id : "ifuinrfin",
        image : "/cour1.png",
        title : "Learn Python",
        description : "Understanding Basic algorithms and data structures with python, and practices on competative programming sites.",
        enroll : "40+ Enroll",
    },    {
        id : "ifuinrfin",
        image : "/cour1.png",
        title : "Learn Python",
        description : "Understanding Basic algorithms and data structures with python, and practices on competative programming sites.",
        enroll : "40+ Enroll",
    },    {
        id : "ifuinrfin",
        image : "/cour1.png",
        title : "Learn Python",
        description : "Understanding Basic algorithms and data structures with python, and practices on competative programming sites.",
        enroll : "40+ Enroll",
    },
]
