export const Profiles = [
    {
        id :"IDUH89398HW",
        image :"profile.png",
        name : "Daniel Kebede",
        title : "BSC in Mathematics",
        cost : "5",
    },
    {
        id :"IDUH89398HW",
        image :"profile.png",
        name : "Daniel Kebede",
        title : "BSC in Mathematics",
        cost : "5",
    },
    {
        id :"IDUH89398HW",
        image :"profile.png",
        name : "Daniel Kebede",
        title : "BSC in Mathematics",
        cost : "5",
    },
    {
        id :"IDUH89398HW",
        image :"profile.png",
        name : "Daniel Kebede",
        title : "BSC in Mathematics",
        cost : "5",
    },
    {
        id :"IDUH89398HW",
        image :"profile.png",
        name : "Daniel Kebede",
        title : "BSC in Mathematics",
        cost : "5",
    },
    {
        id :"IDUH89398HW",
        image :"profile.png",
        name : "Daniel Kebede",
        title : "BSC in Mathematics",
        cost : "5",
    },
    {
        id :"IDUH89398HW",
        image :"profile.png",
        name : "Daniel Kebede",
        title : "BSC in Mathematics",
        cost : "5",
    },
    {
        id :"IDUH89398HW",
        image :"profile.png",
        name : "Daniel Kebede",
        title : "BSC in Mathematics",
        cost : "5",
    },
    {
        id :"IDUH89398HW",
        image :"profile.png",
        name : "Daniel Kebede",
        title : "BSC in Mathematics",
        cost : "5",
    },
    {
        id :"IDUH89398HW",
        image :"profile.png",
        name : "Daniel Kebede",
        title : "BSC in Mathematics",
        cost : "5",
    },
    {
        id :"IDUH89398HW",
        image :"profile.png",
        name : "Daniel Kebede",
        title : "BSC in Mathematics",
        cost : "5",
    },
    {
        id :"IDUH89398HW",
        image :"profile.png",
        name : "Daniel Kebede",
        title : "BSC in Mathematics",
        cost : "5",
    },
    {
        id :"IDUH89398HW",
        image :"profile.png",
        name : "Daniel Kebede",
        title : "BSC in Mathematics",
        cost : "5",
    },
    {
        id :"IDUH89398HW",
        image :"profile.png",
        name : "Daniel Kebede",
        title : "BSC in Mathematics",
        cost : "5",
    },
]



export const Courses = [
    {
        id : "ifuinrfin",
        image : "/cour1.png",
        title : "Learn Python",
        description : "Understanding Basic algorithms and data structures with python, and practices on competative programming sites.",
        enroll : "40+ Enroll",
    },    {
        id : "ifuinrfin",
        image : "/cour1.png",
        title : "Learn Python",
        description : "Understanding Basic algorithms and data structures with python, and practices on competative programming sites.",
        enroll : "40+ Enroll",
    },    {
        id : "ifuinrfin",
        image : "/cour1.png",
        title : "Learn Python",
        description : "Understanding Basic algorithms and data structures with python, and practices on competative programming sites.",
        enroll : "40+ Enroll",
    },    {
        id : "ifuinrfin",
        image : "/cour1.png",
        title : "Learn Python",
        description : "Understanding Basic algorithms and data structures with python, and practices on competative programming sites.",
        enroll : "40+ Enroll",
    },    {
        id : "ifuinrfin",
        image : "/cour1.png",
        title : "Learn Python",
        description : "Understanding Basic algorithms and data structures with python, and practices on competative programming sites.",
        enroll : "40+ Enroll",
    },    {
        id : "ifuinrfin",
        image : "/cour1.png",
        title : "Learn Python",
        description : "Understanding Basic algorithms and data structures with python, and practices on competative programming sites.",
        enroll : "40+ Enroll",
    },    {
        id : "ifuinrfin",
        image : "/cour1.png",
        title : "Learn Python",
        description : "Understanding Basic algorithms and data structures with python, and practices on competative programming sites.",
        enroll : "40+ Enroll",
    },    {
        id : "ifuinrfin",
        image : "/cour1.png",
        title : "Learn Python",
        description : "Understanding Basic algorithms and data structures with python, and practices on competative programming sites.",
        enroll : "40+ Enroll",
    },    {
        id : "ifuinrfin",
        image : "/cour1.png",
        title : "Learn Python",
        description : "Understanding Basic algorithms and data structures with python, and practices on competative programming sites.",
        enroll : "40+ Enroll",
    },    {
        id : "ifuinrfin",
        image : "/cour1.png",
        title : "Learn Python",
        description : "Understanding Basic algorithms and data structures with python, and practices on competative programming sites.",
        enroll : "40+ Enroll",
    },    {
        id : "ifuinrfin",
        image : "/cour1.png",
        title : "Learn Python",
        description : "Understanding Basic algorithms and data structures with python, and practices on competative programming sites.",
        enroll : "40+ Enroll",
    },    {
        id : "ifuinrfin",
        image : "/cour1.png",
        title : "Learn Python",
        description : "Understanding Basic algorithms and data structures with python, and practices on competative programming sites.",
        enroll : "40+ Enroll",
    },    {
        id : "ifuinrfin",
        image : "/cour1.png",
        title : "Learn Python",
        description : "Understanding Basic algorithms and data structures with python, and practices on competative programming sites.",
        enroll : "40+ Enroll",
    },    {
        id : "ifuinrfin",
        image : "/cour1.png",
        title : "Learn Python",
        description : "Understanding Basic algorithms and data structures with python, and practices on competative programming sites.",
        enroll : "40+ Enroll",
    },    {
        id : "ifuinrfin",
        image : "/cour1.png",
        title : "Learn Python",
        description : "Understanding Basic algorithms and data structures with python, and practices on competative programming sites.",
        enroll : "40+ Enroll",
    },    {
        id : "ifuinrfin",
        image : "/cour1.png",
        title : "Learn Python",
        description : "Understanding Basic algorithms and data structures with python, and practices on competative programming sites.",
        enroll : "40+ Enroll",
    },    {
        id : "ifuinrfin",
        image : "/cour1.png",
        title : "Learn Python",
        description : "Understanding Basic algorithms and data structures with python, and practices on competative programming sites.",
        enroll : "40+ Enroll",
    },
]
